{% set name = "TidalPy" %}
{% set version = "0.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tidalpy-{{ version }}.tar.gz
  sha256: 7cd7a9c2b5cb9ed060903895ddef11f50e9d0125cd6122b4f54a1c653f174873

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --no-binary cyrk
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools
    - numpy
    - scipy
    - cython
    - wheel
    - cyrk >=0.13.5
    - pip
  run:
    - python
    - numba
    - scipy
    - platformdirs
    - toml
    - dill
    - psutil
    - pathos
    - cyrk >=0.13.5
    - astropy-base
    - astroquery
    - matplotlib-base
    - ipympl
    - cmcrameri

test:
  imports:
    - TidalPy
  commands:
    - python -c "import TidalPy; print(TidalPy.__version__)"
    - pip check
  requires:
    - pip

about:
  home: www.tidalpy.info/
  summary: Tidal Dynamics and Thermal-Orbital Evolution Software Suite Implemented in Cython and Python
  description: |
    TidalPy provides efficient tools to estimate tidal dissipation within rocky and icy worlds.
    The RaidalSolver package includes tools to calculate a planet or moon's "Love" numbers.
    The Tides package includes tools to estimate tidal heating and spin-orbit evolution including the effects from
    higher-order eccentricity and obliquity terms which are often left out of other models. 
  license: CC-BY-SA-4.0
  license_file: LICENSE.md
  doc_url: https://github.com/jrenaud90/TidalPy/tree/main/Documentation
  dev_url: https://github.com/jrenaud90/TidalPy

extra:
  recipe-maintainers:
    - jrenaud90
